modelo.Usuario=repositoriosModelo.RepositorioUsuarioJPA
modelo.Producto=repositoriosModelo.RepositorioProductosJPA
modelo.Categoria=repositoriosModelo.RepositorioCategoriaJPA

repositoriosAdHoc.RepositorioProductoAdHoc=repositoriosAdHoc.RepositorioProductoAdHocJPA
repositoriosAdHoc.RepositorioUsuarioAdHoc=repositoriosAdHoc.RepositorioUsuarioAdHocJPA
repositoriosAdHoc.RepositorioCategoriasAdHoc=repositoriosAdHoc.RepositorioCategoriasAdHocJPA