modelo.Usuario=repositorio.RepositorioUsuariosJPA
# Añado estos servicios para inyección de dependencias
servicio.IServicioUsuario=servicio.ServicioUsuario
servicio.IServiciosCategorias=servicio.ServicioCategorias
servicio.IServiciosProductos=servicio.ServicioProductos
