modelo.Usuario=repositoriosModelo.RepositorioUsuarioJPA
modelo.Producto=repositoriosModelo.RepositorioProductosJPA
modelo.Categoria=repositoriosModelo.RepositorioCategoriaJPA

repositorio.RepositorioProductoAdHoc=repositorio.RepositorioProductoAdHocJPA
# repositorio.RepositorioUsuarioAdHoc=repositorio.RepositorioUsuarioAdHocJPA # Si tuvieras uno para Usuario